[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks.environment]
NIXPACKS_NODE_VERSION = "22"