[build]
builder = "nixpacks"
buildCommand = "npm install && ./node_modules/.bin/nest build --verbose"

[deploy]
startCommand = "node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
